import { StaticRouter } from "react-router-dom";
import { renderToNodeStream } from "react-dom/server";
import path from "path";
import { ChunkExtractorManager, ChunkExtractor } from "@loadable/server";
import React from "react";
import App from "../client/app.js";
// This is the stats file generated by webpack loadable plugin

const Render = (req, res) => {
  // Render your application
  res.write(
    `<html><head><title>Test</title><meta charset="utf-8">
    <title>Webpack App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <link rel="stylesheet" type="text/css" href="/bundle.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus+SC&family=Roboto&display=swap" rel="stylesheet">
    <style>
        *{ 
            box-sizing: border-box;
            overflow: auto;
            margin:0;
            padding:0;
        }
        h1, h2, h3{
            font-family: "Marcellus SC", sans-serif;
        }
        div{
            font-family: Roboto, sans-serif;
        }
    </style></head><body><div id='root'>`
  );
  const statsFile = path.resolve("./dist/public/loadable-stats.json");
  const chunkExtractor = new ChunkExtractor({
    statsFile,
    entrypoints: ["app"],
  });
  const jsx = chunkExtractor.collectChunks(
    <StaticRouter location={req.url}>
      <App />
    </StaticRouter>
  );
  const stream = renderToNodeStream(jsx);
  // you'd then pipe the stream into the response object until it's done
  stream.pipe(res, { end: false });
  const scripts = chunkExtractor.getScriptTags({ async: false });
  console.log(chunkExtractor.getScriptTags(), "/n/n/n", scripts[0].props);
  // and finalize the response with closing HTML
  stream.on("end", () => res.end(`</div>${scripts}</body></html>`));
};

export default Render;
